// Nexjs
import Head from "next/head";
// React
import { useState } from "react";
// Components
import Map from "../components/Map";
import Filtros from "../components/Filtros";

export default function Home() {
  const [filtro, setFiltro] = useState({
    tipo: "todos",
    hora: new Date().toLocaleTimeString([], {
      hour: "2-digit",
      minute: "2-digit",
    }),
    estrellas: "todos",
  });

  return (
    <>
      <Head>
        <title>Google Map React - Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="main">
        <h1>Titulo</h1>
        <Filtros filtro={filtro} setFiltro={setFiltro} />
        <Map filtro={filtro} />
      </main>
    </>
  );
}
