// Nexjs
import Head from "next/head";
// React
import { useState } from "react";
// Components
import Map from "../components/Map";

export default function Home() {
  const [filtro, setFiltro] = useState("Comida Rápida");

  return (
    <>
      <Head>
        <title>Google Map React - Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Map filtro={filtro} />
      </main>
    </>
  );
}
